Exemple 1: Non,car le premier catch va attraper l'exception et le deuxième catch ne sera pas exécuté.

Exemple 2: Non, car aucun message d'erreur sera transmis pour l'exception attrapé par le catch.